/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * add.java
 *
 * Created on Jul 22, 2011, 2:39:59 PM
 */
package s__d__s;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.*;

/**
 *
 * @author USER
 */
public class add extends javax.swing.JFrame {

    /** Creates new form add */
    public add() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        a13 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        a4 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        a6 = new javax.swing.JTextField();
        a5 = new javax.swing.JTextField();
        a8 = new javax.swing.JTextField();
        a7 = new javax.swing.JTextField();
        a10 = new javax.swing.JTextField();
        a9 = new javax.swing.JTextField();
        a11 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        a14 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        a15 = new javax.swing.JTextField();
        a16 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        a17 = new javax.swing.JTextField();
        a22 = new javax.swing.JTextField();
        a18 = new javax.swing.JTextField();
        a19 = new javax.swing.JTextField();
        a20 = new javax.swing.JTextField();
        a21 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        a12 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        a50 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Database");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 36));
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Student Personal Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 980, 50);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel4.setText("Student ID :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 60, 120, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel5.setText("Department  :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 230, 120, 20);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel24.setText("Student Name  :");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(10, 267, 120, 20);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel25.setText("Year  :");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(10, 310, 120, 17);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel23.setText("Semester :");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(10, 350, 100, 17);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel18.setText("Religion  :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 380, 120, 17);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel6.setText("Father's Name  :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 410, 120, 17);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel26.setText("Occupation  :");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(10, 440, 120, 20);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel21.setText("Mother's Name  :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(10, 477, 120, 20);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel19.setText("Occupation  :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 517, 120, 20);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel28.setText("Hometown :");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(10, 550, 120, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel7.setText("Student Login ID  :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 150, 140, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel8.setText("Blood Group   :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(430, 210, 110, 17);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel29.setText("Date of Birth  :");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(430, 180, 120, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel9.setText("Present Address :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(430, 60, 140, 20);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel27.setText("E - mail  :");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(760, -220, 120, 15);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel20.setText("Contact Number :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(760, -180, 120, 15);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel15.setText("Institute Name :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(310, -240, 88, 15);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel16.setText("Obtained GPA :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(310, -240, 84, 15);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel17.setText("Year of Pass :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(310, -240, 78, 15);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11.setText("Institute Name :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(310, -240, 88, 15);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel12.setText("Obtained GPA :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(310, -240, 84, 15);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel13.setText("Year of Pass :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(310, -240, 78, 15);
        jPanel1.add(a13);
        a13.setBounds(600, 180, 240, 20);
        jPanel1.add(a1);
        a1.setBounds(160, 60, 210, 20);
        jPanel1.add(a4);
        a4.setBounds(160, 310, 90, 20);
        jPanel1.add(a3);
        a3.setBounds(160, 270, 210, 20);

        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });
        jPanel1.add(a6);
        a6.setBounds(160, 380, 210, 20);
        jPanel1.add(a5);
        a5.setBounds(160, 350, 90, 20);
        jPanel1.add(a8);
        a8.setBounds(160, 440, 210, 20);
        jPanel1.add(a7);
        a7.setBounds(160, 410, 210, 20);
        jPanel1.add(a10);
        a10.setBounds(160, 520, 210, 20);
        jPanel1.add(a9);
        a9.setBounds(160, 480, 210, 20);
        jPanel1.add(a11);
        a11.setBounds(160, 550, 210, 20);

        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        jPanel1.add(a2);
        a2.setBounds(160, 230, 210, 20);
        jPanel1.add(a14);
        a14.setBounds(600, 210, 240, 20);

        jLabel30.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel30.setText("E - mail  :");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(430, 240, 120, 20);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel22.setText("Year of Pass   : ");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(430, 470, 130, 17);
        jPanel1.add(a15);
        a15.setBounds(600, 240, 240, 20);

        a16.setText("+880");
        jPanel1.add(a16);
        a16.setBounds(600, 280, 240, 20);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel31.setText("Contact Number :");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(430, 280, 130, 17);

        jLabel32.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel32.setText("School Name :");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(430, 310, 130, 17);

        jLabel33.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel33.setText("SSC GPA :");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(430, 340, 130, 17);

        jLabel34.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel34.setText("Year of Pass :");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(430, 370, 130, 17);

        jLabel35.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel35.setText("College Name :");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(430, 400, 130, 17);

        jLabel36.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel36.setText("HSC GPA  :");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(430, 430, 130, 17);
        jPanel1.add(a17);
        a17.setBounds(600, 310, 240, 20);
        jPanel1.add(a22);
        a22.setBounds(600, 470, 170, 20);
        jPanel1.add(a18);
        a18.setBounds(600, 340, 170, 20);
        jPanel1.add(a19);
        a19.setBounds(600, 370, 170, 20);
        jPanel1.add(a20);
        a20.setBounds(600, 400, 240, 20);
        jPanel1.add(a21);
        a21.setBounds(600, 430, 170, 20);

        a12.setColumns(20);
        a12.setRows(5);
        jScrollPane1.setViewportView(a12);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(600, 66, 240, 100);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(720, 500, 140, 40);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Back");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(770, 560, 100, 23);
        jPanel1.add(a50);
        a50.setBounds(160, 150, 200, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_a6ActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        try {
            Connection conn = getConnection();
            Statement st = conn.createStatement();
            String s = new String();
            s = "insert into smss (id,dept,nam,yer,sem,rel,fnam,foc,mnam,moc,home,add,birth,blood,mail,contact,sin,sgpa,spass,hin,hgpa,hpass,lid ) values ('" + this.a1.getText() + "','" + this.a2.getText() + "','" + this.a3.getText() + "','" + this.a4.getText() + "','" + this.a5.getText() + "','" + this.a6.getText() + "','" + this.a7.getText() + "','" + this.a8.getText() + "','" + this.a9.getText() + "','" + this.a10.getText() + "','" + this.a11.getText() + "','" + this.a12.getText() + "','" + this.a13.getText() + "','" + this.a14.getText() + "','" + this.a15.getText() + "','" + this.a16.getText() + "','" + this.a17.getText() + "','" + this.a18.getText() + "','" + this.a19.getText() + "','" + this.a20.getText() + "','" + this.a21.getText() + "','" + this.a22.getText() + "','" + this.a50.getText() + "')" ;
            st.executeUpdate(s);
            st = conn.createStatement();
            st.close();
            conn.close();
        } catch(Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "Data added successfully");
        this.a1.setText("");
        this.a2.setText("");
        this.a3.setText("");
        this.a4.setText("");
        this.a5.setText("");
        this.a6.setText("");
        this.a7.setText("");
        this.a8.setText("");
        this.a9.setText("");
        this.a10.setText("");
        this.a11.setText("");
        this.a12.setText("");
        this.a13.setText("");
        this.a14.setText("");
        this.a15.setText("");
        this.a16.setText("");
        this.a17.setText("");
        this.a18.setText("");
        this.a19.setText("");
        this.a20.setText("");
        this.a21.setText("");
        this.a22.setText("");
             this.a50.setText("");

        // TODO add your handling code here:
    




        // TODO add your handling code here:
    }                                        
    private static Connection getConnection() throws Exception
    {
    String driver = "sun.jdbc.odbc.JdbcOdbcDriver";
    String url = "jdbc:odbc:sms";
    String username = "";
    String password = "";
    Class.forName(driver);
    return DriverManager.getConnection(url, username, password);

  
}//GEN-LAST:event_AddButtonActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        f002 ob=new f002();
        ob.setVisible(true);
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new add().setVisible(true);
            }
        });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a10;
    private javax.swing.JTextField a11;
    private javax.swing.JTextArea a12;
    private javax.swing.JTextField a13;
    private javax.swing.JTextField a14;
    private javax.swing.JTextField a15;
    private javax.swing.JTextField a16;
    private javax.swing.JTextField a17;
    private javax.swing.JTextField a18;
    private javax.swing.JTextField a19;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a20;
    private javax.swing.JTextField a21;
    private javax.swing.JTextField a22;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JTextField a50;
    private javax.swing.JTextField a6;
    private javax.swing.JTextField a7;
    private javax.swing.JTextField a8;
    private javax.swing.JTextField a9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
