/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * adminmarkview.java
 *
 * Created on Jul 31, 2011, 11:35:44 AM
 */
package s__d__s;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
/**
 *
 * @author USER
 */
public class adminmarkview extends javax.swing.JFrame {

    /** Creates new form adminmarkview */
    public adminmarkview() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        a4 = new javax.swing.JTextField();
        a5 = new javax.swing.JTextField();
        a6 = new javax.swing.JTextField();
        a7 = new javax.swing.JTextField();
        a8 = new javax.swing.JTextField();
        a9 = new javax.swing.JTextField();
        a10 = new javax.swing.JTextField();
        a11 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel14.setText("Enter ID & Course No:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 20, 170, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Average Best 3 Quiz :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 380, 160, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("Quiz 1 : ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 120, 70, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("Quiz 2 : ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 180, 70, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("Quiz 3 : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 240, 70, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setText("Quiz 4 : ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 310, 70, 20);

        jLabel38.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel38.setText("Attendence :");
        jPanel1.add(jLabel38);
        jLabel38.setBounds(360, 110, 71, 30);

        jLabel42.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel42.setText("Semester Final :");
        jPanel1.add(jLabel42);
        jLabel42.setBounds(360, 170, 91, 30);

        jLabel43.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel43.setText("Total Marks :");
        jPanel1.add(jLabel43);
        jLabel43.setBounds(360, 240, 73, 20);

        jLabel41.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel41.setText("GPA :");
        jPanel1.add(jLabel41);
        jLabel41.setBounds(360, 310, 80, 20);

        a1.setFont(new java.awt.Font("Tahoma", 0, 18));
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        jPanel1.add(a1);
        a1.setBounds(190, 30, 240, 30);

        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        jPanel1.add(a3);
        a3.setBounds(190, 120, 120, 20);
        jPanel1.add(a4);
        a4.setBounds(190, 180, 120, 20);
        jPanel1.add(a5);
        a5.setBounds(190, 240, 120, 20);
        jPanel1.add(a6);
        a6.setBounds(190, 310, 120, 20);
        jPanel1.add(a7);
        a7.setBounds(190, 380, 120, 20);
        jPanel1.add(a8);
        a8.setBounds(500, 120, 130, 20);

        a9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a9ActionPerformed(evt);
            }
        });
        jPanel1.add(a9);
        a9.setBounds(500, 180, 130, 20);
        jPanel1.add(a10);
        a10.setBounds(500, 240, 130, 20);
        jPanel1.add(a11);
        a11.setBounds(500, 310, 130, 20);

        jLabel1.setBackground(new java.awt.Color(51, 0, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 30, 110, 30);

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setText("Back");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(520, 410, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_a1ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_a3ActionPerformed

    private void a9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a9ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_a9ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        try {
            Connection conn = getConnection();
            Statement st = conn.createStatement();
            //System.out.println(this.stdidTextField.toString());
            String query = new String();
            
            query = "SELECT * FROM result where a1 = '" + this.a1.getText()+ "'";
            System.out.println(query);
            
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                
                
                this.a3.setText(rs.getString("a3"));
                this.a4.setText(rs.getString("a4"));
                this.a5.setText(rs.getString("a5"));
                this.a6.setText(rs.getString("a6"));
                this.a7.setText(rs.getString("a9"));
                this.a8.setText(rs.getString("a7"));
                this.a9.setText(rs.getString("a8"));
                this.a10.setText(rs.getString("a11"));
                this.a11.setText(rs.getString("a10"));
                
                
            }
            
            st.close();
            conn.close();
        } catch (Exception e ) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    f002 j=new f002();
        j.setVisible(true);
        dispose();
}//GEN-LAST:event_jButton1ActionPerformed
private static Connection getConnection() throws Exception
    {
    String driver = "sun.jdbc.odbc.JdbcOdbcDriver";
    String url = "jdbc:odbc:sms";
    String username = "";
    String password = "";
    Class.forName(driver);
    return DriverManager.getConnection(url, username, password);

  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new adminmarkview().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a10;
    private javax.swing.JTextField a11;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JTextField a6;
    private javax.swing.JTextField a7;
    private javax.swing.JTextField a8;
    private javax.swing.JTextField a9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
