/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * f006.java
 *
 * Created on Jul 17, 2011, 2:36:17 AM
 */
package s__d__s;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */


public class f006 extends javax.swing.JFrame {

    /** Creates new form f006 */
    public f006() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        a6 = new javax.swing.JTextField();
        a7 = new javax.swing.JTextField();
        a4 = new javax.swing.JTextField();
        a5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TEXT = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        a8 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        p1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        p3 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Database System");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setText("Year :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 70, 70, 25);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel4.setText("Student ID :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 30, 66, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel5.setText("Department :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 140, 80, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel6.setText("Course Number  :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 390, 100, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel7.setText("Course Title        :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 440, 100, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel8.setText("Credit Hours      :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 470, 100, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel9.setText("Course Teacher :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 510, 100, 20);

        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        jPanel3.add(a1);
        a1.setBounds(140, 30, 230, 20);

        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        jPanel3.add(a3);
        a3.setBounds(140, 110, 110, 20);
        jPanel3.add(a2);
        a2.setBounds(140, 70, 110, 20);

        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });
        jPanel3.add(a6);
        a6.setBounds(140, 470, 100, 20);
        jPanel3.add(a7);
        a7.setBounds(140, 510, 230, 20);

        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        jPanel3.add(a4);
        a4.setBounds(140, 390, 110, 20);

        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        jPanel3.add(a5);
        a5.setBounds(140, 430, 230, 20);

        jButton2.setFont(new java.awt.Font("Andalus", 1, 14));
        jButton2.setText("Search");
        jPanel3.add(jButton2);
        jButton2.setBounds(560, 260, 77, 31);

        jButton4.setFont(new java.awt.Font("Andalus", 1, 14));
        jButton4.setText("Register");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(280, 550, 90, 31);

        jLabel10.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel10);
        jLabel10.setBounds(0, 10, 400, 50);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(0, -40, 100, 40);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(340, -40, 100, 40);

        TEXT.setColumns(20);
        TEXT.setEditable(false);
        TEXT.setRows(5);
        jScrollPane2.setViewportView(TEXT);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 230, 360, 140);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Available Courses");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 200, 130, 20);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton5.setText("OK");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKbutton(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(290, 140, 80, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel15.setText("Semester :");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(20, 110, 62, 20);
        jPanel3.add(a8);
        a8.setBounds(140, 140, 110, 20);

        jPanel4.setBackground(new java.awt.Color(0, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setLayout(null);

        jButton1.setFont(new java.awt.Font("Andalus", 1, 14));
        jButton1.setText("Search");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(270, 140, 90, 31);

        p1.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(p1);
        p1.setBounds(80, 100, 250, 20);

        jLabel11.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("View Student Registered Courses");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(0, 20, 370, 50);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel12.setText("Student ID :");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(10, 100, 66, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 190, 350, 350);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6);
        jPanel6.setBounds(-30, -40, 100, 40);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel13.setText("Year :");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 140, 50, 20);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel14.setText("Semester :");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(140, 140, 62, 20);
        jPanel4.add(p3);
        p3.setBounds(210, 140, 40, 20);
        jPanel4.add(p2);
        p2.setBounds(80, 140, 40, 20);

        jButton3.setText("Exit");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(10, 543, 350, 40);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Course Registration");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a3ActionPerformed

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a6ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a4ActionPerformed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a5ActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
          try {
            Connection conn = getConnection();
            Statement st = conn.createStatement();
            String s = new String();
            s = "insert into sms (x1,x2,x3,x4,x5,x6,x7,x8 ) values ('" + this.a1.getText() + "','" + this.a2.getText() + "','" + this.a3.getText() + "','" + this.a4.getText() + "','" + this.a5.getText() + "','" + this.a6.getText() + "','" + this.a7.getText() + "','" + this.a8.getText() + "')" ;
            st.executeUpdate(s);
            st = conn.createStatement();
            st.close();
            conn.close();
        } catch(Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "Data added successfully");
        this.a1.setText("");
        this.a2.setText("");
        this.a3.setText("");
        this.a4.setText("");
        this.a5.setText("");
        this.a6.setText("");
        this.a7.setText("");
        this.a8.setText("");
     
        // TODO add your handling code here:
    




        // TODO add your handling code here:
    }                                        
    private static Connection getConnection() throws Exception
    {
    String driver = "sun.jdbc.odbc.JdbcOdbcDriver";
    String url = "jdbc:odbc:sms";
    String username = "";
    String password = "";
    Class.forName(driver);
    return DriverManager.getConnection(url, username, password);

  }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new f006().setVisible(true);
            }
        });
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void jTextArea1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1AncestorAdded

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void OKbutton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKbutton
        // TODO add your handling code here:
        //a2a3a8
     //if (strcmp(a2,2)){};
       //  int i=a2.compareTo(a3);
       
    }//GEN-LAST:event_OKbutton

    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TEXT;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JTextField a6;
    private javax.swing.JTextField a7;
    private javax.swing.JTextField a8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    // End of variables declaration//GEN-END:variables
}
