/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * stdview.java
 *
 * Created on Jul 26, 2011, 10:46:04 AM
 */
package s__d__s;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
/**
 *
 * @author Nishat
 */
public class stdview extends javax.swing.JFrame {

    /** Creates new form stdview */
    public stdview() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        a13 = new javax.swing.JTextField();
        a4 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        a6 = new javax.swing.JTextField();
        a5 = new javax.swing.JTextField();
        a8 = new javax.swing.JTextField();
        a7 = new javax.swing.JTextField();
        a10 = new javax.swing.JTextField();
        a9 = new javax.swing.JTextField();
        a11 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        a14 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        a15 = new javax.swing.JTextField();
        a16 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        a12 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        a20 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        a21 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        a22 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        a17 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        a18 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        a19 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        a50 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Personal Database");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 153, 204));

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 36));
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Personal Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 980, 50);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel5.setText("Department  :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 270, 120, 20);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel24.setText("Student ID  :");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(10, 140, 120, 20);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel25.setText("Year  :");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(10, 310, 120, 17);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel23.setText("Semester :");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(10, 350, 100, 17);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel18.setText("Religion  :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 380, 120, 17);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel6.setText("Father's Name  :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 410, 120, 17);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel26.setText("Occupation  :");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(10, 440, 120, 20);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel21.setText("Mother's Name  :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(10, 477, 120, 20);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel19.setText("Occupation  :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 517, 120, 20);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel28.setText("Hometown :");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(10, 550, 120, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel8.setText("Blood Group   :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 100, 110, 17);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel29.setText("Date of Birth  :");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(420, 60, 120, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel9.setText("Present Address :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 580, 140, 20);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel27.setText("E - mail  :");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(760, -220, 120, 15);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel20.setText("Contact Number :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(760, -180, 120, 15);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel15.setText("Institute Name :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(310, -240, 88, 15);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel16.setText("Obtained GPA :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(310, -240, 84, 15);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel17.setText("Year of Pass :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(310, -240, 78, 15);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11.setText("Institute Name :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(310, -240, 88, 15);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel12.setText("Obtained GPA :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(310, -240, 84, 15);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel13.setText("Year of Pass :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(310, -240, 78, 15);

        a13.setEditable(false);
        jPanel1.add(a13);
        a13.setBounds(600, 60, 240, 20);

        a4.setEditable(false);
        jPanel1.add(a4);
        a4.setBounds(160, 310, 130, 20);

        a3.setEditable(false);
        jPanel1.add(a3);
        a3.setBounds(160, 270, 210, 20);

        a6.setEditable(false);
        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });
        jPanel1.add(a6);
        a6.setBounds(160, 380, 210, 20);

        a5.setEditable(false);
        jPanel1.add(a5);
        a5.setBounds(160, 350, 90, 20);

        a8.setEditable(false);
        jPanel1.add(a8);
        a8.setBounds(160, 440, 210, 20);

        a7.setEditable(false);
        jPanel1.add(a7);
        a7.setBounds(160, 410, 210, 20);

        a10.setEditable(false);
        jPanel1.add(a10);
        a10.setBounds(160, 520, 210, 20);

        a9.setEditable(false);
        jPanel1.add(a9);
        a9.setBounds(160, 480, 210, 20);

        a11.setEditable(false);
        jPanel1.add(a11);
        a11.setBounds(160, 550, 210, 20);

        a2.setEditable(false);
        jPanel1.add(a2);
        a2.setBounds(150, 80, 210, 20);

        a14.setEditable(false);
        jPanel1.add(a14);
        a14.setBounds(600, 100, 240, 20);

        jLabel30.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel30.setText("E - mail  :");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(420, 143, 120, 17);

        a15.setEditable(false);
        jPanel1.add(a15);
        a15.setBounds(600, 140, 240, 20);

        a16.setEditable(false);
        jPanel1.add(a16);
        a16.setBounds(600, 170, 240, 20);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel31.setText("Contact Number :");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(420, 170, 130, 17);

        a12.setColumns(20);
        a12.setEditable(false);
        a12.setRows(5);
        jScrollPane1.setViewportView(a12);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(160, 580, 210, 100);

        jPanel4.setLayout(null);
        jPanel1.add(jPanel4);
        jPanel4.setBounds(320, 310, 0, 0);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HSC");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 160, 460, 20);

        jPanel5.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel35.setText("Institute Name :");
        jPanel5.add(jLabel35);
        jLabel35.setBounds(20, 20, 130, 17);

        a20.setEditable(false);
        jPanel5.add(a20);
        a20.setBounds(160, 20, 230, 20);

        jLabel36.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel36.setText("Obtained GPA :");
        jPanel5.add(jLabel36);
        jLabel36.setBounds(20, 50, 130, 17);

        a21.setEditable(false);
        jPanel5.add(a21);
        a21.setBounds(160, 50, 170, 20);

        jLabel34.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel34.setText("Year of Pass :");
        jPanel5.add(jLabel34);
        jLabel34.setBounds(20, 80, 130, 17);

        a22.setEditable(false);
        a22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a22ActionPerformed(evt);
            }
        });
        jPanel5.add(a22);
        a22.setBounds(160, 80, 170, 20);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, 180, 460, 140);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SSC");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(0, 0, 460, 17);

        jPanel6.setLayout(null);

        jLabel37.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel37.setText("Institute Name :");
        jPanel6.add(jLabel37);
        jLabel37.setBounds(20, 20, 130, 17);

        a17.setEditable(false);
        jPanel6.add(a17);
        a17.setBounds(160, 20, 240, 20);

        jLabel38.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel38.setText("Obtained GPA :");
        jPanel6.add(jLabel38);
        jLabel38.setBounds(20, 50, 130, 17);

        a18.setEditable(false);
        jPanel6.add(a18);
        a18.setBounds(160, 50, 170, 20);

        jLabel39.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel39.setText("Year of Pass :");
        jPanel6.add(jLabel39);
        jLabel39.setBounds(20, 80, 130, 17);

        a19.setEditable(false);
        a19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a19ActionPerformed(evt);
            }
        });
        jPanel6.add(a19);
        a19.setBounds(160, 80, 170, 20);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(0, 20, 460, 140);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(420, 260, 460, 320);

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Educational Background");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 220, 280, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Enter Login ID :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(420, 590, 90, 40);
        jPanel1.add(a50);
        a50.setBounds(520, 600, 250, 20);

        jLabel32.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel32.setText("Student Name  :");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(10, 80, 120, 20);

        a1.setEditable(false);
        jPanel1.add(a1);
        a1.setBounds(150, 140, 210, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Enter");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(780, 600, 100, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Back");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(800, 670, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_a6ActionPerformed

    private void a22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a22ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_a22ActionPerformed

    private void a19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a19ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_a19ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
               Connection conn = getConnection();
               Statement st = conn.createStatement();
            //System.out.println(this.stdidTextField.toString());
            String query = new String();
           
            query = "SELECT * FROM smss where lid = '" + this.a50.getText()+ "'";
            System.out.println(query);
            
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) 
            {
                this.a1.setText(rs.getString("id"));
                this.a2.setText(rs.getString("nam"));
                this.a3.setText(rs.getString("dept"));
                this.a4.setText(rs.getString("yer"));
                this.a5.setText(rs.getString("sem"));
                this.a6.setText(rs.getString("rel"));
                this.a7.setText(rs.getString("fnam"));
                this.a8.setText(rs.getString("foc"));
                this.a9.setText(rs.getString("mnam"));
                this.a10.setText(rs.getString("moc"));
                this.a11.setText(rs.getString("home"));
                this.a12.setText(rs.getString("add"));
                this.a13.setText(rs.getString("birth"));
                this.a14.setText(rs.getString("blood"));
                this.a15.setText(rs.getString("mail"));
                this.a16.setText(rs.getString("contact"));
                this.a17.setText(rs.getString("sin"));
                this.a18.setText(rs.getString("sgpa"));
                this.a19.setText(rs.getString("spass"));
                this.a20.setText(rs.getString("hin"));
                this.a21.setText(rs.getString("hgpa"));
                this.a22.setText(rs.getString("hpass"));
                 
                
                
                               
            }
            
            st.close();
            conn.close();
        }
        catch (Exception e ) 
        {
          e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        studentpg op= new studentpg();
        op.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
private static Connection getConnection() throws Exception
    {
    String driver = "sun.jdbc.odbc.JdbcOdbcDriver";
    String url = "jdbc:odbc:sms";
    String username = "";
    String password = "";
    Class.forName(driver);
    return DriverManager.getConnection(url, username, password);

  
}      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new stdview().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a10;
    private javax.swing.JTextField a11;
    private javax.swing.JTextArea a12;
    private javax.swing.JTextField a13;
    private javax.swing.JTextField a14;
    private javax.swing.JTextField a15;
    private javax.swing.JTextField a16;
    private javax.swing.JTextField a17;
    private javax.swing.JTextField a18;
    private javax.swing.JTextField a19;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a20;
    private javax.swing.JTextField a21;
    private javax.swing.JTextField a22;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JTextField a50;
    private javax.swing.JTextField a6;
    private javax.swing.JTextField a7;
    private javax.swing.JTextField a8;
    private javax.swing.JTextField a9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
