/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * teacher1.java
 *
 * Created on Jul 26, 2011, 5:13:34 AM
 */
package s__d__s;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Maruf
 */
public class teacher1 extends javax.swing.JFrame {

    /** Creates new form teacher1 */
    public teacher1() {
        initComponents();
        pan.setVisible(false);
         pan2.setVisible(false);
         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEXT = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        pan2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teacher Database");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Teacher Database Access");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 761, 45);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Teacher ID :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 120, 72, 22);
        jPanel1.add(a1);
        a1.setBounds(120, 120, 140, 20);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Search");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 120, 90, 30);

        pan.setBackground(new java.awt.Color(153, 153, 153));
        pan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pan.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Courses Under you are :");
        pan.add(jLabel3);
        jLabel3.setBounds(20, 20, 170, 14);

        TEXT.setBackground(new java.awt.Color(204, 204, 204));
        TEXT.setColumns(20);
        TEXT.setEditable(false);
        TEXT.setRows(5);
        jScrollPane1.setViewportView(TEXT);

        pan.add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 280, 220);

        jPanel1.add(pan);
        pan.setBounds(430, 120, 320, 310);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Sign Out");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(600, 450, 150, 30);

        pan2.setBackground(new java.awt.Color(153, 153, 153));
        pan2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Enter Your Course Title");
        pan2.add(jLabel4);
        jLabel4.setBounds(10, 40, 220, 15);

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        pan2.add(b1);
        b1.setBounds(10, 80, 340, 20);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setText("Course No 1");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course1ActionPerformed(evt);
            }
        });
        pan2.add(jButton3);
        jButton3.setBounds(10, 130, 130, 23);

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setText("Course No 3");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course3ActionPerformed(evt);
            }
        });
        pan2.add(jButton5);
        jButton5.setBounds(10, 180, 130, 23);

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setText("Course No 4");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course4ActionPerformed(evt);
            }
        });
        pan2.add(jButton6);
        jButton6.setBounds(210, 180, 140, 23);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setText("Course No 2");
        jButton4.setActionCommand("");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course2actionPerformed(evt);
            }
        });
        pan2.add(jButton4);
        jButton4.setBounds(210, 130, 140, 23);

        jPanel1.add(pan2);
        pan2.setBounds(20, 220, 370, 240);

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setText("Back");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(653, 60, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            
            Connection conn = getConnection();
            Statement st = conn.createStatement();
            String query = new String();
            
            query = "SELECT * FROM teach where tid = '" + this.a1.getText()+"'";
            
            
            ResultSet rs = st.executeQuery(query);
            
            
         
            while (rs.next()) {
                   String a1 = rs.getString("crsno1");
                   String a2 = rs.getString("crsnam1");
                   String a3 = rs.getString("crsno2");
                   String a4 = rs.getString("crsnam2");
                   String a5 = rs.getString("crsno3");
                   String a6 = rs.getString("crsnam3");
                   String a7 = rs.getString("crsno4");
                   String a8 = rs.getString("crsnam4");
         
         this.TEXT.setText("\tCourse No 1    \n\n"+"Course Title    :"+"    "+a1+"\n\n\n"+"Course Name  :"+"    "+a2+"\n\n\n\tCourse No 2\n\n"+"Course Title    :"+"    "+a3+"\n\n\n"+"Course Name  :"+"    "+a4+"\n\n\n\tCourse No 3\n\n"+"Course Title    :"+"    "+a5+"\n\n\n"+"Course Name  :"+"    "+a6+"\n\n\n\tCourse No 4\n\n"+"Course Title    :"+"    "+a7+"\n\n\n"+"Course Name  :"+"    "+a8+"\n\n\n");
         
         pan.setVisible(true);
         pan2.setVisible(true);
         
            }
            st.close();
            conn.close();
        } catch (Exception e ) {
            e.printStackTrace();
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        login ob=new login();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Course1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course1ActionPerformed
       
        
        
       try {
            Connection conn = getConnection();
            Statement st = conn.createStatement(); 
            String i= new String(); 
            String j = new String();
     
            String query = new String();
            
            query = "SELECT * FROM teach where crsno1 = '" + this.b1.getText()+ "'";
       
            ResultSet rs1 = st.executeQuery(query);
      
              if (rs1.next())
            {
                 i = rs1.getString("crsno1");
                 j=rs1.getString("tid");
              
                   f007 o=new f007();
                   o.setVisible(true);
     
            }
            else{JOptionPane.showMessageDialog(null,"Wrong Course Entry !");}
              
              
            st = conn.createStatement();
            st.close();
            conn.close();
            } 
       catch(Exception e) {
            e.printStackTrace();
        }
      

          
    }//GEN-LAST:event_Course1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void Course3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course3ActionPerformed
        // TODO add your handling code here:
         try {
            Connection conn = getConnection();
            Statement st = conn.createStatement(); 
            String i= new String(); 
            String j = new String();
     
            String query = new String();
            
            query = "SELECT * FROM teach where crsno3 = '" + this.b1.getText()+ "'";
       
            ResultSet rs1 = st.executeQuery(query);
      
              if (rs1.next())
            {
                 i = rs1.getString("crsno3");
                 j=rs1.getString("tid");
              
                   f007 o=new f007();
                   o.setVisible(true);
     
            }
            else{JOptionPane.showMessageDialog(null,"Wrong Course Entry !");}
              
              
            st = conn.createStatement();
            st.close();
            conn.close();
            } 
       catch(Exception e) {
            e.printStackTrace();
        }
      
    }//GEN-LAST:event_Course3ActionPerformed

    private void Course4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course4ActionPerformed
        // TODO add your handling code here:
         try {
            Connection conn = getConnection();
            Statement st = conn.createStatement(); 
            String i= new String(); 
            String j = new String();
     
            String query = new String();
            
            query = "SELECT * FROM teach where crsno4 = '" + this.b1.getText()+ "'";
       
            ResultSet rs1 = st.executeQuery(query);
      
              if(rs1.next())
            {
                 i = rs1.getString("crsno4");
                 j=rs1.getString("tid");
              
                   f007 o=new f007();
                   o.setVisible(true);
     
            }
              else{JOptionPane.showMessageDialog(null,"Wrong Course Entry !");}
            
              
              
            st = conn.createStatement();
            st.close();
            conn.close();
            } 
       catch(Exception e) {
            e.printStackTrace();
        }
      
    }//GEN-LAST:event_Course4ActionPerformed

    private void Course2actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course2actionPerformed
        // TODO add your handling code here:
           try {
            Connection conn = getConnection();
            Statement st = conn.createStatement(); 
            String i= new String(); 
            String j = new String();
     
            String query = new String();
            
            query = "SELECT * FROM teach where crsno2 = '" + this.b1.getText()+ "'";
       
            ResultSet rs1 = st.executeQuery(query);
      
              if (rs1.next())
            {
                 i = rs1.getString("crsno2");
                 j=rs1.getString("tid");
              
                   f007 o=new f007();
                   o.setVisible(true);
     
            }
            else{JOptionPane.showMessageDialog(null,"Wrong Course Entry !");}
              
              
            st = conn.createStatement();
            st.close();
            conn.close();
            } 
       catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Course2actionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dispose();
        teacher2 o=new teacher2();
        o.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private static Connection getConnection() throws Exception
    {
    String driver = "sun.jdbc.odbc.JdbcOdbcDriver";
    String url = "jdbc:odbc:sms";
    String username = "";
    String password = "";
    Class.forName(driver);
    return DriverManager.getConnection(url, username, password);

  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new teacher1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TEXT;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField b1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pan;
    private javax.swing.JPanel pan2;
    // End of variables declaration//GEN-END:variables
}
